[build]
  command = "yarn install && yarn prisma:generate && yarn migrate"
  functions = "functions"
  publish = "functions"


[functions]

[functions.postInvoices]
  external_node_modules = [
    "module-one",
    "module-two"
  ]

[functions.getInvoices]
  external_node_modules = [
    "module-one",
    "module-two"
  ]

[functions.updateInvoice]
  external_node_modules = [
    "module-one",
    "module-two"
  ]

[functions.deleteInvoice]
  external_node_modules = [
    "module-one",
    "module-two"
  ]
