[build]
  command = "yarn install && yarn build"
  functions = "functions"
  publish = "dist"

[functions]
  [functions.api]
    external_node_modules = [
      "module-one",
      "module-two"
    ]
