[build]
  command = "yarn install && yarn prisma:generate"
  functions = "functions"
  publish = "dist"

[functions]
  [functions.invoices]
    handler = "functions/invoices.handler"
    external_node_modules = ["@prisma/client"]

