[build]
  command = "yarn install && yarn prisma:generate && yarn migrate"
  functions = "functions"
  publish = "functions"


[functions]
  [functions.invoices]
    handler = "functions/invoices.handler"
